[package]
name = "BucketPeriphery"
version = "0.6.0"
edition = "legacy"
published-at = "0xf84a73f667f65dbc54483b8c456defc3ebc4e469026e5e8b4c2a0f3ff4a8748d"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
BucketProtocol = { git = "../v1-core", subdir = "protocol/", rev = "mainnet" }

[addresses]
bucket_periphery = "0x0"
# bucket_periphery = "0xb3f10f2c9a52b615ab8b0b930ee55e019bacb407b29f5f534e6d9c3291341db8"
