[package]
name = "BucketPeriphery"
version = "0.6.0"
edition = "legacy"
published-at = "0xa1f1e93a392f011c69175d9064f5c4cb45ecd46468c1c9f537d3efa1d021cb95"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
BucketProtocol = { git = "../v1-core", subdir = "protocol/", rev = "mainnet" }

[addresses]
bucket_periphery = "0x0"
# bucket_periphery = "0xb3f10f2c9a52b615ab8b0b930ee55e019bacb407b29f5f534e6d9c3291341db8"
