[package]
name = "BucketPeriphery"
edition = "2024.beta"

[dependencies]
BucketProtocol = { local = "../v1-core/protocol" }
StrapFountain = { local = "../strap-fountain" }

[addresses]
bucket_periphery = "0x0"
# bucket_periphery = "0xb3f10f2c9a52b615ab8b0b930ee55e019bacb407b29f5f534e6d9c3291341db8"
